### ISSUE TITLE
Hi, New and wanted to know something

### ISSUE THREAD

**Issue by thegreatmihai** [Xiloe/Odin-Paladins#2]
Can I have some esp for Paladins ? XD

**Comment by Nom-Youtube** [comment]
lmao, just make it yourself, there's plently of threads on stuff like that on uc.

**Comment by thegreatmihai** [comment]
What is uc ? And I don't know how to make it myself, I'm not that old and intelligent for that kind of stuff

**Comment by Xiloe** [comment]
Lol, like I'm old.. And why would you make an issue on a paladins cheat full source to ask that? Just update the SDK and compile it yourself lmfao.. or look at the code. Btw google is your friend, there are plenty of resources, threads and awesome peeps for that.
